### ISSUE TITLE
Delete unnecessary files

### ISSUE THREAD

**Issue by ecoppen** [Kashof1/Programming-challenges#1]
__pycache__ not required, for example

**Comment by Kashof1** [comment]
I will delete pycache. The .dstore files are added automatically by Mac, so I'll have to untrack them, otherwise they'll add themselves whenever I push the folder to github. I'm not sure how to untrack them, so I would appreciate some help on that front.

**Comment by ecoppen** [comment]
That's the purpose of the  `.gitignore` file in the main directory, it should already be setup to do that - perhaps you don't have the file in your local directory?

https://github.com/Kashof1/Programming-challenges/blob/acbeadf6867d16dd98b275e141399175e862a066/.gitignore#L2

**Comment by Kashof1** [comment]
I've been pushing through the proprietary plugin on VSCode. I'll make the fix in the .gitignore file during study. Thanks!
