### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by ecoppen** [Kashof1/Programming-challenges#4]
https://github.com/Kashof1/Programming-challenges/blob/acbeadf6867d16dd98b275e141399175e862a066/Brampton%20Manor%20Academy/1%20-%20ROD%20CONVERSIONS/main.py#L24

Put the input in it's own function. Why? Validation. If they enter a string or a negative number, they should be recursively asked to enter another value.

**Comment by Kashof1** [comment]
if you shift the input into the function, how would you then test the function in the separate testing file? to test it before, I was passing the values that I wanted to test against into the function in the testing file. if i take inputs from within the function, i would not be passing any values into the function, and that would mean that i cannot test it the same way. How would you go on to test the function if it takes input internally?

**Comment by ecoppen** [comment]
According to the current version, you're not actually testing the `run` function at all? https://github.com/Kashof1/Programming-challenges/blob/main/Brampton%20Manor%20Academy/1%20-%20ROD%20CONVERSIONS/testing.py
Your tests are only accessing each of the calculation functions, which is correct. When you run the testing file, the inputs are already programmed into it e.g. https://github.com/Kashof1/Programming-challenges/blob/acbeadf6867d16dd98b275e141399175e862a066/Brampton%20Manor%20Academy/1%20-%20ROD%20CONVERSIONS/testing.py#L9 where 1 is the input.

**Comment by Kashof1** [comment]
I've added validation to the input (within the input function)
