### ISSUE TITLE
f string padding

### ISSUE THREAD

**Issue by ecoppen** [Kashof1/Programming-challenges#5]
https://github.com/Kashof1/Programming-challenges/blob/c9a0b993aee598c523eb7057286b46f7913d200e/Brampton%20Manor%20Academy/2%20-%20RICHTER/main.py#L11

https://github.com/Kashof1/Programming-challenges/blob/c9a0b993aee598c523eb7057286b46f7913d200e/Brampton%20Manor%20Academy/2%20-%20RICHTER/main.py#L6

This code looks good, minor improvement with f string padding: https://saralgyaan.com/posts/f-string-in-python-usage-guide/#How_to_add_space_padding_in_Python_f-strings?

**Comment by Kashof1** [comment]
done
