### ISSUE TITLE
https://code-with-me.global.jetbrains.com/MioRdQgnNzHUZJu0ug4Qzg#p=PY&fp=170B7B0B5488F87732AC99FCFF5D6443E803C0B05DDE0C41CD429F606401D5D6

### ISSUE THREAD

**Issue by yxnagi** [Kashof1/Programming-challenges#6]

**Comment by Kashof1** [comment]
thanks

**Comment by yxnagi** [comment]
https://code-with-me.global.jetbrains.com/u9faJv_QTROVBeGGC2-cBA#p=PY&fp=170B7B0B5488F87732AC99FCFF5D6443E803C0B05DDE0C41CD429F606401D5D6

**Comment by yxnagi** [comment]
https://code-with-me.global.jetbrains.com/ULX_62_E8lX0EkTHisNDbQ#p=PY&fp=14E29FBE6919519CB2DDD8D03D326A53ABBF1F2C80733C7FD74CC5523A19379B
